### ISSUE TITLE
Possible activity leaking?

### ISSUE THREAD

**Issue by realdadfish** [frogermcs/Dagger2Recipes-ActivitiesMultibinding#1]
I love the example you've given here, because it really solves some real-world testing problems I had to work around in the past with crude hacks like overriding `AndroidJUnitRunner.newActivity(...)` and the like.

However, I fear that your example implementation might leak activities. Since you inject a `Map<Activity, ActivityBuilder>` in your `Application` class, I bet Dagger will create a regular `HashMap` and not a `WeakHashMap` instance for you. If the latter would be used, you'd also have to apply a couple of more null checks.

**Comment by frogermcs** [comment]
@tommyd3mdi we inject `Map<Class<? extends Activity>, ActivityComponentBuilder>`, so the keys here are class literals, not objects. And even if you don't want to use them from any reasony, you can also use Strings or Integers if that works for you. You can define keys here:
https://github.com/frogermcs/Dagger2Recipes-ActivitiesMultibinding/blob/master/app/src/main/java/com/frogermcs/recipes/dagger_activities_multibinding/di/activity/ActivityBindingModule.java

**Comment by realdadfish** [comment]
Ah, ok, then I read this wrong, sorry, the blog post only had the `@ActivityKey` annotation without the value. Thanks for clearing that up!

**Comment by emredirican** [comment]
When I used this approach in my project, I realized that LeakCanary points out to the activity leaks. After that, I tried it with this example and it is the same issue. 
I think the component builder holds reference to the activity module, which holds reference to the activity. 

@frogermcs Have you experienced such issue in your projects or any ideas about it? Thanks.

**Comment by frogermcs** [comment]
@emredirican thanks for pointing this out. I've just updated example code and changed Activity reference to WeakReference in `ActivityModule` class.
I've also raised a ticket in Dagger repository to try to find another solution for your issue: https://github.com/google/dagger/issues/505
